application: ancient-tractor-91116
version: 1
runtime: php
api_version: 1
module: default

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /(.+\.php)$
  script: \1

- url: /(\w+\.html)$
  static_files: \1
  upload: (\w+\.html)
  mime_type: text/html

- url: /
  script: sign_in.php

- url: /.*
  script: not_found.php
